version: "3.9"  # optional since v1.27.0
services:
  fs-testing-dashboard-client:
    image: fs-testing-dashboard-client
    ports:
      - 5001:5001
    environment:
      - API_URL=http://fs-testing-dashboard-server:5000
      - NGINX_PORT=80
      - CURRENT_IP=172.104.156.42
  
  fs-testing-dashboard-server:
    image: fs-testing-dashboard-server
    volumes:
      - ./data:/data
    ports:
      - 5000:5000
    environment:
      - REPORTS_DIRECTORY=/data/reports
      - CLIENT_DOWNLOADER_LOGS_DIRECTORY=/data/logs
      - MONGO_USERNAME=mongo
      - MONGO_PASSWORD=123
      - MONGO_HOST=mongo
  
  nginx:
    image: nginx
    volumes:
      - ./data/reports:/usr/share/nginx/html
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
  
  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=123
 

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongo
      - ME_CONFIG_MONGODB_ADMINPASSWORD=123
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:123@mongo:27017/
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=123